services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=dima
      - POSTGRES_PASSWORD=qseft135
      - POSTGRES_DB=fastapi_app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

